# Site settings

client:
  name: Germany National Tourist Board
  link: "http://www.germany.travel/en/"

description: >
  Discover a winter wonderland in Germany. From fairytale castles to unmissable pistes, a winter in this beguiling land promises unforgettable adventures. Picturesque medieval villages and bustling modern cities are waiting to be explored, filling your itinerary with inspired winter moments. Choose your winter in Germany here.



uk:
  site-title: Winter in Germany
  client-link: http://www.germany.travel/en/
  core-se-link: https://www.secretescapes.com/current-sales
  core-nav:
    - title: Current Sales
      link: https://www.secretescapes.com/current-sales
    - title: Spa
      link: https://www.secretescapes.com/spa
    - title: Smart Stays
      link: https://www.secretescapes.com/smartstays/filter
nl:
  site-title: Winter in Duitsland
  client-link: http://www.germany.travel/en/
  core-se-link: https://www.secretescapes.com/current-sales
  core-nav:
    - title: Huidige sales
      link: link
    - title: Wellness
      link: link
    - title: Smart Stays
      link: link
be:
  site-title: Winter in Duitsland
  client-link: http://www.germany.travel/en/
  core-se-link: https://www.secretescapes.com/current-sales
  core-nav:
    - title: Huidige sales
      link: link
    - title: Wellness
      link: link
    - title: Smart Stays
      link: link



# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/winter-in-germany" # the subpath of your site, e.g. /blog/
img:     "/winter-in-germany/_assets/img"
css:     "/winter-in-germany/_assets/css"
js:      "/winter-in-germany/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed